CREATE TABLE hechos_ataques (
    id_ataque INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    id_origen INT,
    id_destino INT,
    id_protocolo INT,
    id_tipo_trafico INT,
    id_malware INT,
    id_anomalia INT,
    id_severidad INT,
    id_dispositivo INT,
    id_segmento INT,
    id_geo INT,
    longitud_paquete INT,
    numero_alertas INT,
    FOREIGN KEY (id_origen) REFERENCES dim_origen(id_origen),
    FOREIGN KEY (id_destino) REFERENCES dim_destino(id_destino),
    FOREIGN KEY (id_protocolo) REFERENCES dim_protocolo(id_protocolo),
    FOREIGN KEY (id_tipo_trafico) REFERENCES dim_tipo_trafico(id_tipo_trafico),
    FOREIGN KEY (id_malware) REFERENCES dim_malware(id_malware),
    FOREIGN KEY (id_anomalia) REFERENCES dim_anomalia(id_anomalia),
    FOREIGN KEY (id_severidad) REFERENCES dim_severidad(id_severidad),
    FOREIGN KEY (id_dispositivo) REFERENCES dim_dispositivo(id_dispositivo),
    FOREIGN KEY (id_segmento) REFERENCES dim_segmento(id_segmento),
    FOREIGN KEY (id_geo) REFERENCES dim_geo(id_geo)
);
